export const PATH_BREADCRUMBS: Record<string, string> = {
  "admin-dashboard": "Dashboard",
  "admin-managers": "Managers",
  "admin-accountants": "Accountants",
  "admin-executives": "Executives",
  "catalog": "Catalog",
  "categories": "Categories",
  "sub-categories": "Sub Categories",
  "brands": "Brands",
  "specifications": "Specifications",
  "items": "Items",
  "accountants": "Accountants",
  "executives": "Executives",
  "sellers": "Sellers",
  "product-managers": "Product Managers",
  "service-providers": "Service Providers",
  "buyers": "Buyers",
  "reports": "Reports",
  "general": "General",
  "team": "Team",
  "billing": "Billing",
  "limits": "Limits",
  "ai": "AI",
  "conference-hall": "Conference Hall",
  "calculators": "Calculators",
  "calculator": "Calculator",
  "settings": "Settings",
};
