export enum USER_ROLE {
  ADMIN = "ADMIN",
  ADMIN_MANAGER = "ADMIN_MANAGER",
  ADMIN_ACCOUNTANT = "ADMIN_ACCOUNTANT",
  ADMIN_EXECUTIVE = "ADMIN_EXECUTIVE",
  USER_PRODUCT_SELLER_ADMIN = "USER_PRODUCT_SELLER_ADMIN",
  USER_PRODUCT_SELLER_STAFF = "USER_PRODUCT_SELLER_STAFF",
  USER_SERVICE_PROVIDER_ADMIN = "USER_SERVICE_PROVIDER_ADMIN",
  USER_SERVICE_PROVIDER_STAFF = "USER_SERVICE_PROVIDER_STAFF",
  USER_BUYER_ADMIN = "USER_BUYER_ADMIN",
  UNASSIGNED = "UNASSIGNED",
}
