/**
 * Centralized Enums for consistency across the application.
 * These reflect the backend enum structure and provide human-readable labels.
 */

export enum USER_ROLE {
  ADMIN = "ADMIN",
  ADMIN_MANAGER = "ADMIN_MANAGER",
  ADMIN_ACCOUNTANT = "ADMIN_ACCOUNTANT",
  ADMIN_EXECUTIVE = "ADMIN_EXECUTIVE",
  USER_PRODUCT_SELLER_ADMIN = "USER_PRODUCT_SELLER_ADMIN",
  USER_PRODUCT_SELLER_STAFF = "USER_PRODUCT_SELLER_STAFF",
  USER_SERVICE_PROVIDER_ADMIN = "USER_SERVICE_PROVIDER_ADMIN",
  USER_SERVICE_PROVIDER_STAFF = "USER_SERVICE_PROVIDER_STAFF",
  USER_BUYER_ADMIN = "USER_BUYER_ADMIN",
  UNASSIGNED = "UNASSIGNED",
}

export const USER_ROLE_LABELS: Record<USER_ROLE, string> = {
  [USER_ROLE.ADMIN]: "Admin",
  [USER_ROLE.ADMIN_MANAGER]: "Admin Manager",
  [USER_ROLE.ADMIN_ACCOUNTANT]: "Admin Accountant",
  [USER_ROLE.ADMIN_EXECUTIVE]: "Admin Executive",
  [USER_ROLE.USER_PRODUCT_SELLER_ADMIN]: "Product Seller",
  [USER_ROLE.USER_PRODUCT_SELLER_STAFF]: "Product Seller's Staff",
  [USER_ROLE.USER_SERVICE_PROVIDER_ADMIN]: "Service Provider",
  [USER_ROLE.USER_SERVICE_PROVIDER_STAFF]: "Service Provider's Staff",
  [USER_ROLE.USER_BUYER_ADMIN]: "Buyer",
  [USER_ROLE.UNASSIGNED]: "Unassigned",
};

export enum ENTITY_TYPE {
  MANUFACTURER = "MANUFACTURER",
  WHOLESALER = "WHOLESALER",
  RETAILER = "RETAILER",
  SERVICE_PROVIDER = "SERVICE_PROVIDER",
}

export const ENTITY_TYPE_LABELS: Record<ENTITY_TYPE, string> = {
  [ENTITY_TYPE.MANUFACTURER]: "Manufacturer",
  [ENTITY_TYPE.WHOLESALER]: "Wholesaler",
  [ENTITY_TYPE.RETAILER]: "Retailer",
  [ENTITY_TYPE.SERVICE_PROVIDER]: "Service Provider",
};

export enum VERIFICATION_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PAUSED = "PAUSED",
  REVISE = "REVISE",
  MISINFORMATION = "MISINFORMATION",
  INAPPROPRIATE = "INAPPROPRIATE",
  OTHER = "OTHER",
}

export const VERIFICATION_STATUS_LABELS: Record<VERIFICATION_STATUS, string> = {
  [VERIFICATION_STATUS.PENDING]: "Pending",
  [VERIFICATION_STATUS.APPROVED]: "Approved",
  [VERIFICATION_STATUS.REJECTED]: "Rejected",
  [VERIFICATION_STATUS.PAUSED]: "Paused",
  [VERIFICATION_STATUS.REVISE]: "Revise",
  [VERIFICATION_STATUS.MISINFORMATION]: "Misinformation",
  [VERIFICATION_STATUS.INAPPROPRIATE]: "Inappropriate",
  [VERIFICATION_STATUS.OTHER]: "Other",
};

export enum ITEM_TYPE {
  PRODUCT = "PRODUCT",
  SERVICE = "SERVICE",
}

export const ITEM_TYPE_LABELS: Record<ITEM_TYPE, string> = {
  [ITEM_TYPE.PRODUCT]: "Product",
  [ITEM_TYPE.SERVICE]: "Service",
};

export enum UNIT_TYPE {
  Nos = "Nos",
  Meter = "Meter",
  Feet = "Feet",
  Kilogram = "Kilogram",
  Litre = "Litre",
  SquareMeter = "SquareMeter",
  SquareFeet = "SquareFeet",
  CubicMeter = "CubicMeter",
  CubicFeet = "CubicFeet",
  Bag_50_KG = "Bag_50_KG",
}

export const UNIT_TYPE_LABELS: Record<UNIT_TYPE, string> = {
  [UNIT_TYPE.Nos]: "Nos",
  [UNIT_TYPE.Meter]: "Meter",
  [UNIT_TYPE.Feet]: "Feet",
  [UNIT_TYPE.Kilogram]: "Kilogram",
  [UNIT_TYPE.Litre]: "Litre",
  [UNIT_TYPE.SquareMeter]: "Square Meter",
  [UNIT_TYPE.SquareFeet]: "Square Feet",
  [UNIT_TYPE.CubicMeter]: "Cubic Meter",
  [UNIT_TYPE.CubicFeet]: "Cubic Feet",
  [UNIT_TYPE.Bag_50_KG]: "Bag (50 kg)",
};

export enum ACTIVITY_TYPE {
  ENQUIRY_ASSIGNMENT = "ENQUIRY_ASSIGNMENT",
  APPOINTMENT_ASSIGNMENT = "APPOINTMENT_ASSIGNMENT",
}

export const ACTIVITY_TYPE_LABELS: Record<ACTIVITY_TYPE, string> = {
  [ACTIVITY_TYPE.ENQUIRY_ASSIGNMENT]: "Enquiry Assignment",
  [ACTIVITY_TYPE.APPOINTMENT_ASSIGNMENT]: "Appointment Assignment",
};

export enum NOTIFICATION_TYPE {
  ENQUIRY_SUMBIT = "ENQUIRY_SUMBIT",
  ENQUIRY_RECEIVE = "ENQUIRY_RECEIVE",
  ENQUIRY_REVISE_REQUEST = "ENQUIRY_REVISE_REQUEST",
  QUOTATION_SUMBIT = "QUOTATION_SUMBIT",
  QUOTATION_ACCEPT = "QUOTATION_ACCEPT",
  QUOTATION_REJECT = "QUOTATION_REJECT",
  APPOINTMENT_SUBMIT = "APPOINTMENT_SUBMIT",
  APPOINTMENT_RECEIVE = "APPOINTMENT_RECEIVE",
  VISIT_SUBMIT = "VISIT_SUBMIT",
  VISIT_ACCEPT = "VISIT_ACCEPT",
  VISIT_REJECT = "VISIT_REJECT",
  CHANNEL_VERIFICATION = "CHANNEL_VERIFICATION",
  CONTENT_VERIFICATION = "CONTENT_VERIFICATION",
  EVENT_VERIFICATION = "EVENT_VERIFICATION",
  OFFER_VERIFICATION = "OFFER_VERIFICATION",
  NEW_OFFER = "NEW_OFFER",
  NEW_EVENT = "NEW_EVENT",
  NEW_CONTENT = "NEW_CONTENT",
}

export const NOTIFICATION_TYPE_LABELS: Record<NOTIFICATION_TYPE, string> = {
  [NOTIFICATION_TYPE.ENQUIRY_SUMBIT]: "Enquiry Submitted",
  [NOTIFICATION_TYPE.ENQUIRY_RECEIVE]: "Enquiry Received",
  [NOTIFICATION_TYPE.ENQUIRY_REVISE_REQUEST]: "Enquiry Revise Request",
  [NOTIFICATION_TYPE.QUOTATION_SUMBIT]: "Quotation Submitted",
  [NOTIFICATION_TYPE.QUOTATION_ACCEPT]: "Quotation Accepted",
  [NOTIFICATION_TYPE.QUOTATION_REJECT]: "Quotation Rejected",
  [NOTIFICATION_TYPE.APPOINTMENT_SUBMIT]: "Appointment Submitted",
  [NOTIFICATION_TYPE.APPOINTMENT_RECEIVE]: "Appointment Received",
  [NOTIFICATION_TYPE.VISIT_SUBMIT]: "Visit Submitted",
  [NOTIFICATION_TYPE.VISIT_ACCEPT]: "Visit Accepted",
  [NOTIFICATION_TYPE.VISIT_REJECT]: "Visit Rejected",
  [NOTIFICATION_TYPE.CHANNEL_VERIFICATION]: "Channel Verification",
  [NOTIFICATION_TYPE.CONTENT_VERIFICATION]: "Content Verification",
  [NOTIFICATION_TYPE.EVENT_VERIFICATION]: "Event Verification",
  [NOTIFICATION_TYPE.OFFER_VERIFICATION]: "Offer Verification",
  [NOTIFICATION_TYPE.NEW_OFFER]: "New Offer",
  [NOTIFICATION_TYPE.NEW_EVENT]: "New Event",
  [NOTIFICATION_TYPE.NEW_CONTENT]: "New Content",
};

export enum NOTIFICATION_CHANNEL_TYPE {
  EMAIL = "EMAIL",
  SMS = "SMS",
  WHATSAPP = "WHATSAPP",
  PUSH = "PUSH",
}

export const NOTIFICATION_CHANNEL_TYPE_LABELS: Record<
  NOTIFICATION_CHANNEL_TYPE,
  string
> = {
  [NOTIFICATION_CHANNEL_TYPE.EMAIL]: "Email",
  [NOTIFICATION_CHANNEL_TYPE.SMS]: "SMS",
  [NOTIFICATION_CHANNEL_TYPE.WHATSAPP]: "WhatsApp",
  [NOTIFICATION_CHANNEL_TYPE.PUSH]: "Push Notification",
};

export enum TRANSACTION_REASON {
  QUOTATION_SUMBIT = "QUOTATION_SUMBIT",
  VISIT_SUBMIT = "VISIT_SUBMIT",
  OFFER_PUBLISH = "OFFER_PUBLISH",
  EVENT_PUBLISH = "EVENT_PUBLISH",
  EVENT_JOIN = "EVENT_JOIN",
  CONTENT_PUBLISH = "CONTENT_PUBLISH",
  WALLET_TOPUP = "WALLET_TOPUP",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  REFUND = "REFUND",
  BONUS = "BONUS",
}

export const TRANSACTION_REASON_LABELS: Record<TRANSACTION_REASON, string> = {
  [TRANSACTION_REASON.QUOTATION_SUMBIT]: "Quotation Submission",
  [TRANSACTION_REASON.VISIT_SUBMIT]: "Visit Submission",
  [TRANSACTION_REASON.OFFER_PUBLISH]: "Offer Publication",
  [TRANSACTION_REASON.EVENT_PUBLISH]: "Event Publication",
  [TRANSACTION_REASON.EVENT_JOIN]: "Event Joining",
  [TRANSACTION_REASON.CONTENT_PUBLISH]: "Content Publication",
  [TRANSACTION_REASON.WALLET_TOPUP]: "Wallet Topup",
  [TRANSACTION_REASON.MANUAL_ADJUSTMENT]: "Manual Adjustment",
  [TRANSACTION_REASON.REFUND]: "Refund",
  [TRANSACTION_REASON.BONUS]: "Bonus",
};

export enum REF_TYPE {
  ENQUIRY = "ENQUIRY",
  QUOTATION = "QUOTATION",
  APPOINTMENT = "APPOINTMENT",
  OFFER = "OFFER",
  EVENT = "EVENT",
  EVENT_PARTICIPANT = "EVENT_PARTICIPANT",
  VISIT = "VISIT",
  CONTENT = "CONTENT",
}

export const REF_TYPE_LABELS: Record<REF_TYPE, string> = {
  [REF_TYPE.ENQUIRY]: "Enquiry",
  [REF_TYPE.QUOTATION]: "Quotation",
  [REF_TYPE.APPOINTMENT]: "Appointment",
  [REF_TYPE.OFFER]: "Offer",
  [REF_TYPE.EVENT]: "Event",
  [REF_TYPE.EVENT_PARTICIPANT]: "Event Participant",
  [REF_TYPE.VISIT]: "Visit",
  [REF_TYPE.CONTENT]: "Content",
};

export enum SUPPORT_QUERY_PRIORITY {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export const SUPPORT_QUERY_PRIORITY_LABELS: Record<
  SUPPORT_QUERY_PRIORITY,
  string
> = {
  [SUPPORT_QUERY_PRIORITY.LOW]: "Low",
  [SUPPORT_QUERY_PRIORITY.MEDIUM]: "Medium",
  [SUPPORT_QUERY_PRIORITY.HIGH]: "High",
  [SUPPORT_QUERY_PRIORITY.CRITICAL]: "Critical",
};

export enum SUPPORT_QUERY_STATUS {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export const SUPPORT_QUERY_STATUS_LABELS: Record<SUPPORT_QUERY_STATUS, string> =
  {
    [SUPPORT_QUERY_STATUS.OPEN]: "Open",
    [SUPPORT_QUERY_STATUS.ASSIGNED]: "Assigned",
    [SUPPORT_QUERY_STATUS.IN_PROGRESS]: "In Progress",
    [SUPPORT_QUERY_STATUS.RESOLVED]: "Resolved",
    [SUPPORT_QUERY_STATUS.CLOSED]: "Closed",
  };
