/**
 * Centralized Enums for consistency across the application.
 * These reflect the backend enum structure and provide human-readable labels.
 */

export enum USER_ROLE {
  ADMIN = "ADMIN",
  ADMIN_MANAGER = "ADMIN_MANAGER",
  ADMIN_ACCOUNTANT = "ADMIN_ACCOUNTANT",
  ADMIN_EXECUTIVE = "ADMIN_EXECUTIVE",
  USER_PRODUCT_SELLER_ADMIN = "USER_PRODUCT_SELLER_ADMIN",
  USER_PRODUCT_SELLER_STAFF = "USER_PRODUCT_SELLER_STAFF",
  USER_SERVICE_PROVIDER_ADMIN = "USER_SERVICE_PROVIDER_ADMIN",
  USER_SERVICE_PROVIDER_STAFF = "USER_SERVICE_PROVIDER_STAFF",
  USER_BUYER_ADMIN = "USER_BUYER_ADMIN",
  UNASSIGNED = "UNASSIGNED",
}

export const USER_ROLE_LABELS: Record<USER_ROLE, string> = {
  [USER_ROLE.ADMIN]: "Admin",
  [USER_ROLE.ADMIN_MANAGER]: "Admin Manager",
  [USER_ROLE.ADMIN_ACCOUNTANT]: "Admin Accountant",
  [USER_ROLE.ADMIN_EXECUTIVE]: "Admin Executive",
  [USER_ROLE.USER_PRODUCT_SELLER_ADMIN]: "Product Seller",
  [USER_ROLE.USER_PRODUCT_SELLER_STAFF]: "Product Seller's Staff",
  [USER_ROLE.USER_SERVICE_PROVIDER_ADMIN]: "Service Provider",
  [USER_ROLE.USER_SERVICE_PROVIDER_STAFF]: "Service Provider's Staff",
  [USER_ROLE.USER_BUYER_ADMIN]: "Buyer",
  [USER_ROLE.UNASSIGNED]: "Unassigned",
};

export enum ENTITY_TYPE {
  MANUFACTURER = "MANUFACTURER",
  WHOLESALER = "WHOLESALER",
  RETAILER = "RETAILER",
  SERVICE_PROVIDER = "SERVICE_PROVIDER",
}

export const ENTITY_TYPE_LABELS: Record<ENTITY_TYPE, string> = {
  [ENTITY_TYPE.MANUFACTURER]: "Manufacturer",
  [ENTITY_TYPE.WHOLESALER]: "Wholesaler",
  [ENTITY_TYPE.RETAILER]: "Retailer",
  [ENTITY_TYPE.SERVICE_PROVIDER]: "Service Provider",
};

export enum VERIFICATION_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PAUSED = "PAUSED",
  REVISE = "REVISE",
  MISINFORMATION = "MISINFORMATION",
  INAPPROPRIATE = "INAPPROPRIATE",
  OTHER = "OTHER",
}

export const VERIFICATION_STATUS_LABELS: Record<VERIFICATION_STATUS, string> = {
  [VERIFICATION_STATUS.PENDING]: "Pending",
  [VERIFICATION_STATUS.APPROVED]: "Approved",
  [VERIFICATION_STATUS.REJECTED]: "Rejected",
  [VERIFICATION_STATUS.PAUSED]: "Paused",
  [VERIFICATION_STATUS.REVISE]: "Revise",
  [VERIFICATION_STATUS.MISINFORMATION]: "Misinformation",
  [VERIFICATION_STATUS.INAPPROPRIATE]: "Inappropriate",
  [VERIFICATION_STATUS.OTHER]: "Other",
};

export enum ITEM_TYPE {
  PRODUCT = "PRODUCT",
  SERVICE = "SERVICE",
}

export const ITEM_TYPE_LABELS: Record<ITEM_TYPE, string> = {
  [ITEM_TYPE.PRODUCT]: "Product",
  [ITEM_TYPE.SERVICE]: "Service",
};

export enum UNIT_TYPE {
  Nos = "Nos",
  Meter = "Meter",
  Feet = "Feet",
  Kilogram = "Kilogram",
  Litre = "Litre",
  SquareMeter = "SquareMeter",
  SquareFeet = "SquareFeet",
  CubicMeter = "CubicMeter",
  CubicFeet = "CubicFeet",
  Pouch = "Pouch",
  Box = "Box",
  Bag_50_KG = "Bag_50_KG",
  Milligram = "Milligram",
  Gram = "Gram",
  MetricTon = "MetricTon",
  Ounce = "Ounce",
  Pound = "Pound",
  Quintal = "Quintal",
  Carat = "Carat",
  Grain = "Grain",
  Tola = "Tola",
  Millilitre = "Millilitre",
  CubicCentimetre = "CubicCentimetre",
  FluidOunce = "FluidOunce",
  Gallon = "Gallon",
  Pint = "Pint",
  Quart = "Quart",
  Barrel = "Barrel",
  Millimetre = "Millimetre",
  Centimetre = "Centimetre",
  Kilometre = "Kilometre",
  Inch = "Inch",
  Yard = "Yard",
  Mile = "Mile",
  SquareMillimetre = "SquareMillimetre",
  SquareCentimetre = "SquareCentimetre",
  SquareYard = "SquareYard",
  Acre = "Acre",
  Hectare = "Hectare",
  Decimal = "Decimal",
  Bigha = "Bigha",
  Katha = "Katha",
  Guntha = "Guntha",
  Piece = "Piece",
  Unit = "Unit",
  Item = "Item",
  Pair = "Pair",
  Set = "Set",
  Pack = "Pack",
  Packet = "Packet",
  Carton = "Carton",
  Bundle = "Bundle",
  Roll = "Roll",
  Tube = "Tube",
  Stick = "Stick",
  Bottle = "Bottle",
  Can = "Can",
  Jar = "Jar",
  Bag = "Bag",
  Sack = "Sack",
  Basket = "Basket",
  Tray = "Tray",
  Sleeve = "Sleeve",
  Strip = "Strip",
  BlisterPack = "BlisterPack",
  Capsule = "Capsule",
  Tablet = "Tablet",
  Vial = "Vial",
  Ampoule = "Ampoule",
  Sheet = "Sheet",
  Book = "Book",
  Copy = "Copy",
  Ream = "Ream",
  Coil = "Coil",
  Dozen = "Dozen",
  HalfDozen = "HalfDozen",
  Gross = "Gross",
  Score = "Score",
  Sachet = "Sachet",
  Tin = "Tin",
  Drum = "Drum",
  Container = "Container",
  Crate = "Crate",
  Pallet = "Pallet",
  Tank = "Tank",
  BundlePack = "BundlePack",
  ComboPack = "ComboPack",
  Multipack = "Multipack",
  CubicYard = "CubicYard",
  RunningFoot = "RunningFoot",
  RunningMetre = "RunningMetre",
  Kilolitre = "Kilolitre",
  CubicInch = "CubicInch",
  CubicMillimetre = "CubicMillimetre",
  Plant = "Plant",
  Sapling = "Sapling",
  Seed = "Seed",
  Head = "Head",
  Bird = "Bird",
  License = "License",
  Subscription = "Subscription",
  User = "User",
  Seat = "Seat",
  Download = "Download",
  Watt = "Watt",
  Kilowatt = "Kilowatt",
  KilowattHour = "KilowattHour",
  Ampere = "Ampere",
  Volt = "Volt",
  VA = "VA",
  Second = "Second",
  Minute = "Minute",
  Hour = "Hour",
  Day = "Day",
  Month = "Month",
  Year = "Year",
  Service = "Service",
  Job = "Job",
  Project = "Project",
  Lot = "Lot",
  Consignment = "Consignment",
  AssortedPack = "AssortedPack",
}

export const UNIT_TYPE_LABELS: Record<UNIT_TYPE, string> = {
  [UNIT_TYPE.Nos]: "Nos",
  [UNIT_TYPE.Meter]: "Meter",
  [UNIT_TYPE.Feet]: "Feet",
  [UNIT_TYPE.Kilogram]: "Kilogram",
  [UNIT_TYPE.Litre]: "Litre",
  [UNIT_TYPE.SquareMeter]: "Square Meter",
  [UNIT_TYPE.SquareFeet]: "Square Feet",
  [UNIT_TYPE.CubicMeter]: "Cubic Meter",
  [UNIT_TYPE.CubicFeet]: "Cubic Feet",
  [UNIT_TYPE.Pouch]: "Pouch",
  [UNIT_TYPE.Box]: "Box",
  [UNIT_TYPE.Bag_50_KG]: "Bag (50 kg)",
  [UNIT_TYPE.Milligram]: "Milligram",
  [UNIT_TYPE.Gram]: "Gram",
  [UNIT_TYPE.MetricTon]: "Metric Ton",
  [UNIT_TYPE.Ounce]: "Ounce",
  [UNIT_TYPE.Pound]: "Pound",
  [UNIT_TYPE.Quintal]: "Quintal",
  [UNIT_TYPE.Carat]: "Carat",
  [UNIT_TYPE.Grain]: "Grain",
  [UNIT_TYPE.Tola]: "Tola",
  [UNIT_TYPE.Millilitre]: "Millilitre",
  [UNIT_TYPE.CubicCentimetre]: "Cubic Centimetre",
  [UNIT_TYPE.FluidOunce]: "Fluid Ounce",
  [UNIT_TYPE.Gallon]: "Gallon",
  [UNIT_TYPE.Pint]: "Pint",
  [UNIT_TYPE.Quart]: "Quart",
  [UNIT_TYPE.Barrel]: "Barrel",
  [UNIT_TYPE.Millimetre]: "Millimetre",
  [UNIT_TYPE.Centimetre]: "Centimetre",
  [UNIT_TYPE.Kilometre]: "Kilometre",
  [UNIT_TYPE.Inch]: "Inch",
  [UNIT_TYPE.Yard]: "Yard",
  [UNIT_TYPE.Mile]: "Mile",
  [UNIT_TYPE.SquareMillimetre]: "Square Millimetre",
  [UNIT_TYPE.SquareCentimetre]: "Square Centimetre",
  [UNIT_TYPE.SquareYard]: "Square Yard",
  [UNIT_TYPE.Acre]: "Acre",
  [UNIT_TYPE.Hectare]: "Hectare",
  [UNIT_TYPE.Decimal]: "Decimal",
  [UNIT_TYPE.Bigha]: "Bigha",
  [UNIT_TYPE.Katha]: "Katha",
  [UNIT_TYPE.Guntha]: "Guntha",
  [UNIT_TYPE.Piece]: "Piece",
  [UNIT_TYPE.Unit]: "Unit",
  [UNIT_TYPE.Item]: "Item",
  [UNIT_TYPE.Pair]: "Pair",
  [UNIT_TYPE.Set]: "Set",
  [UNIT_TYPE.Pack]: "Pack",
  [UNIT_TYPE.Packet]: "Packet",
  [UNIT_TYPE.Carton]: "Carton",
  [UNIT_TYPE.Bundle]: "Bundle",
  [UNIT_TYPE.Roll]: "Roll",
  [UNIT_TYPE.Tube]: "Tube",
  [UNIT_TYPE.Stick]: "Stick",
  [UNIT_TYPE.Bottle]: "Bottle",
  [UNIT_TYPE.Can]: "Can",
  [UNIT_TYPE.Jar]: "Jar",
  [UNIT_TYPE.Bag]: "Bag",
  [UNIT_TYPE.Sack]: "Sack",
  [UNIT_TYPE.Basket]: "Basket",
  [UNIT_TYPE.Tray]: "Tray",
  [UNIT_TYPE.Sleeve]: "Sleeve",
  [UNIT_TYPE.Strip]: "Strip",
  [UNIT_TYPE.BlisterPack]: "Blister Pack",
  [UNIT_TYPE.Capsule]: "Capsule",
  [UNIT_TYPE.Tablet]: "Tablet",
  [UNIT_TYPE.Vial]: "Vial",
  [UNIT_TYPE.Ampoule]: "Ampoule",
  [UNIT_TYPE.Sheet]: "Sheet",
  [UNIT_TYPE.Book]: "Book",
  [UNIT_TYPE.Copy]: "Copy",
  [UNIT_TYPE.Ream]: "Ream",
  [UNIT_TYPE.Coil]: "Coil",
  [UNIT_TYPE.Dozen]: "Dozen",
  [UNIT_TYPE.HalfDozen]: "Half Dozen",
  [UNIT_TYPE.Gross]: "Gross",
  [UNIT_TYPE.Score]: "Score",
  [UNIT_TYPE.Sachet]: "Sachet",
  [UNIT_TYPE.Tin]: "Tin",
  [UNIT_TYPE.Drum]: "Drum",
  [UNIT_TYPE.Container]: "Container",
  [UNIT_TYPE.Crate]: "Crate",
  [UNIT_TYPE.Pallet]: "Pallet",
  [UNIT_TYPE.Tank]: "Tank",
  [UNIT_TYPE.BundlePack]: "Bundle Pack",
  [UNIT_TYPE.ComboPack]: "Combo Pack",
  [UNIT_TYPE.Multipack]: "Multipack",
  [UNIT_TYPE.CubicYard]: "Cubic Yard",
  [UNIT_TYPE.RunningFoot]: "Running Foot",
  [UNIT_TYPE.RunningMetre]: "Running Metre",
  [UNIT_TYPE.Kilolitre]: "Kilolitre",
  [UNIT_TYPE.CubicInch]: "Cubic Inch",
  [UNIT_TYPE.CubicMillimetre]: "Cubic Millimetre",
  [UNIT_TYPE.Plant]: "Plant",
  [UNIT_TYPE.Sapling]: "Sapling",
  [UNIT_TYPE.Seed]: "Seed",
  [UNIT_TYPE.Head]: "Head",
  [UNIT_TYPE.Bird]: "Bird",
  [UNIT_TYPE.License]: "License",
  [UNIT_TYPE.Subscription]: "Subscription",
  [UNIT_TYPE.User]: "User",
  [UNIT_TYPE.Seat]: "Seat",
  [UNIT_TYPE.Download]: "Download",
  [UNIT_TYPE.Watt]: "Watt",
  [UNIT_TYPE.Kilowatt]: "Kilowatt",
  [UNIT_TYPE.KilowattHour]: "Kilowatt-hour",
  [UNIT_TYPE.Ampere]: "Ampere",
  [UNIT_TYPE.Volt]: "Volt",
  [UNIT_TYPE.VA]: "VA",
  [UNIT_TYPE.Second]: "Second",
  [UNIT_TYPE.Minute]: "Minute",
  [UNIT_TYPE.Hour]: "Hour",
  [UNIT_TYPE.Day]: "Day",
  [UNIT_TYPE.Month]: "Month",
  [UNIT_TYPE.Year]: "Year",
  [UNIT_TYPE.Service]: "Service",
  [UNIT_TYPE.Job]: "Job",
  [UNIT_TYPE.Project]: "Project",
  [UNIT_TYPE.Lot]: "Lot",
  [UNIT_TYPE.Consignment]: "Consignment",
  [UNIT_TYPE.AssortedPack]: "Assorted Pack",
};

export enum ACTIVITY_TYPE {
  ENQUIRY_ASSIGNMENT = "ENQUIRY_ASSIGNMENT",
  APPOINTMENT_ASSIGNMENT = "APPOINTMENT_ASSIGNMENT",
}

export const ACTIVITY_TYPE_LABELS: Record<ACTIVITY_TYPE, string> = {
  [ACTIVITY_TYPE.ENQUIRY_ASSIGNMENT]: "Enquiry Assignment",
  [ACTIVITY_TYPE.APPOINTMENT_ASSIGNMENT]: "Appointment Assignment",
};

export enum ENQUIRY_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export const ENQUIRY_STATUS_LABELS: Record<ENQUIRY_STATUS, string> = {
  [ENQUIRY_STATUS.PENDING]: "Pending",
  [ENQUIRY_STATUS.APPROVED]: "Approved",
  [ENQUIRY_STATUS.REJECTED]: "Rejected",
  [ENQUIRY_STATUS.COMPLETED]: "Completed",
  [ENQUIRY_STATUS.CANCELLED]: "Cancelled",
};

export enum QUOTATION_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  REVISED = "REVISED",
  REVISE_REQUESTED = "REVISE_REQUESTED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export const QUOTATION_STATUS_LABELS: Record<QUOTATION_STATUS, string> = {
  [QUOTATION_STATUS.PENDING]: "Pending",
  [QUOTATION_STATUS.ACCEPTED]: "Accepted",
  [QUOTATION_STATUS.REJECTED]: "Rejected",
  [QUOTATION_STATUS.REVISED]: "Revised",
  [QUOTATION_STATUS.REVISE_REQUESTED]: "Revision Requested",
  [QUOTATION_STATUS.EXPIRED]: "Expired",
  [QUOTATION_STATUS.CANCELLED]: "Cancelled",
};

export enum PRICE_CHANGE_TYPE {
  INCREASED = "INCREASED",
  DECREASED = "DECREASED",
  MAINTAINED = "MAINTAINED",
}

export enum NOTIFICATION_TYPE {
  ENQUIRY_SUMBIT = "ENQUIRY_SUMBIT",
  ENQUIRY_RECEIVE = "ENQUIRY_RECEIVE",
  ENQUIRY_REVISE_REQUEST = "ENQUIRY_REVISE_REQUEST",
  QUOTATION_SUMBIT = "QUOTATION_SUMBIT",
  QUOTATION_ACCEPT = "QUOTATION_ACCEPT",
  QUOTATION_REJECT = "QUOTATION_REJECT",
  FAKE_ENQUIRY_FLAGGED = "FAKE_ENQUIRY_FLAGGED",
  APPOINTMENT_SUBMIT = "APPOINTMENT_SUBMIT",
  APPOINTMENT_RECEIVE = "APPOINTMENT_RECEIVE",
  VISIT_SUBMIT = "VISIT_SUBMIT",
  VISIT_ACCEPT = "VISIT_ACCEPT",
  VISIT_REJECT = "VISIT_REJECT",
  CHANNEL_VERIFICATION = "CHANNEL_VERIFICATION",
  CONTENT_VERIFICATION = "CONTENT_VERIFICATION",
  EVENT_VERIFICATION = "EVENT_VERIFICATION",
  OFFER_VERIFICATION = "OFFER_VERIFICATION",
  NEW_OFFER = "NEW_OFFER",
  NEW_EVENT = "NEW_EVENT",
  NEW_CONTENT = "NEW_CONTENT",
}

export const NOTIFICATION_TYPE_LABELS: Record<NOTIFICATION_TYPE, string> = {
  [NOTIFICATION_TYPE.ENQUIRY_SUMBIT]: "Enquiry Submitted",
  [NOTIFICATION_TYPE.ENQUIRY_RECEIVE]: "Enquiry Received",
  [NOTIFICATION_TYPE.ENQUIRY_REVISE_REQUEST]: "Enquiry Revise Request",
  [NOTIFICATION_TYPE.QUOTATION_SUMBIT]: "Quotation Submitted",
  [NOTIFICATION_TYPE.QUOTATION_ACCEPT]: "Quotation Accepted",
  [NOTIFICATION_TYPE.QUOTATION_REJECT]: "Quotation Rejected",
  [NOTIFICATION_TYPE.FAKE_ENQUIRY_FLAGGED]: "Fake Enquiry Flagged",
  [NOTIFICATION_TYPE.APPOINTMENT_SUBMIT]: "Appointment Submitted",
  [NOTIFICATION_TYPE.APPOINTMENT_RECEIVE]: "Appointment Received",
  [NOTIFICATION_TYPE.VISIT_SUBMIT]: "Visit Submitted",
  [NOTIFICATION_TYPE.VISIT_ACCEPT]: "Visit Accepted",
  [NOTIFICATION_TYPE.VISIT_REJECT]: "Visit Rejected",
  [NOTIFICATION_TYPE.CHANNEL_VERIFICATION]: "Channel Verification",
  [NOTIFICATION_TYPE.CONTENT_VERIFICATION]: "Content Verification",
  [NOTIFICATION_TYPE.EVENT_VERIFICATION]: "Event Verification",
  [NOTIFICATION_TYPE.OFFER_VERIFICATION]: "Offer Verification",
  [NOTIFICATION_TYPE.NEW_OFFER]: "New Offer",
  [NOTIFICATION_TYPE.NEW_EVENT]: "New Event",
  [NOTIFICATION_TYPE.NEW_CONTENT]: "New Content",
};

export enum NOTIFICATION_CHANNEL_TYPE {
  EMAIL = "EMAIL",
  SMS = "SMS",
  WHATSAPP = "WHATSAPP",
  PUSH = "PUSH",
}

export const NOTIFICATION_CHANNEL_TYPE_LABELS: Record<
  NOTIFICATION_CHANNEL_TYPE,
  string
> = {
  [NOTIFICATION_CHANNEL_TYPE.EMAIL]: "Email",
  [NOTIFICATION_CHANNEL_TYPE.SMS]: "SMS",
  [NOTIFICATION_CHANNEL_TYPE.WHATSAPP]: "WhatsApp",
  [NOTIFICATION_CHANNEL_TYPE.PUSH]: "Push Notification",
};

export enum TRANSACTION_REASON {
  QUOTATION_SUMBIT = "QUOTATION_SUMBIT",
  VISIT_SUBMIT = "VISIT_SUBMIT",
  OFFER_PUBLISH = "OFFER_PUBLISH",
  EVENT_PUBLISH = "EVENT_PUBLISH",
  EVENT_JOIN = "EVENT_JOIN",
  CONTENT_PUBLISH = "CONTENT_PUBLISH",
  WALLET_TOPUP = "WALLET_TOPUP",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  REFUND = "REFUND",
  BONUS = "BONUS",
}

export const TRANSACTION_REASON_LABELS: Record<TRANSACTION_REASON, string> = {
  [TRANSACTION_REASON.QUOTATION_SUMBIT]: "Quotation Submission",
  [TRANSACTION_REASON.VISIT_SUBMIT]: "Visit Submission",
  [TRANSACTION_REASON.OFFER_PUBLISH]: "Offer Publication",
  [TRANSACTION_REASON.EVENT_PUBLISH]: "Event Publication",
  [TRANSACTION_REASON.EVENT_JOIN]: "Event Joining",
  [TRANSACTION_REASON.CONTENT_PUBLISH]: "Content Publication",
  [TRANSACTION_REASON.WALLET_TOPUP]: "Wallet Topup",
  [TRANSACTION_REASON.MANUAL_ADJUSTMENT]: "Manual Adjustment",
  [TRANSACTION_REASON.REFUND]: "Refund",
  [TRANSACTION_REASON.BONUS]: "Bonus",
};

export enum REF_TYPE {
  ENQUIRY = "ENQUIRY",
  QUOTATION = "QUOTATION",
  APPOINTMENT = "APPOINTMENT",
  OFFER = "OFFER",
  EVENT = "EVENT",
  EVENT_PARTICIPANT = "EVENT_PARTICIPANT",
  VISIT = "VISIT",
  CONTENT = "CONTENT",
}

export const REF_TYPE_LABELS: Record<REF_TYPE, string> = {
  [REF_TYPE.ENQUIRY]: "Enquiry",
  [REF_TYPE.QUOTATION]: "Quotation",
  [REF_TYPE.APPOINTMENT]: "Appointment",
  [REF_TYPE.OFFER]: "Offer",
  [REF_TYPE.EVENT]: "Event",
  [REF_TYPE.EVENT_PARTICIPANT]: "Event Participant",
  [REF_TYPE.VISIT]: "Visit",
  [REF_TYPE.CONTENT]: "Content",
};

export enum SUPPORT_QUERY_PRIORITY {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export const SUPPORT_QUERY_PRIORITY_LABELS: Record<
  SUPPORT_QUERY_PRIORITY,
  string
> = {
  [SUPPORT_QUERY_PRIORITY.LOW]: "Low",
  [SUPPORT_QUERY_PRIORITY.MEDIUM]: "Medium",
  [SUPPORT_QUERY_PRIORITY.HIGH]: "High",
  [SUPPORT_QUERY_PRIORITY.CRITICAL]: "Critical",
};

export enum SUPPORT_QUERY_STATUS {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export const SUPPORT_QUERY_STATUS_LABELS: Record<SUPPORT_QUERY_STATUS, string> =
  {
    [SUPPORT_QUERY_STATUS.OPEN]: "Open",
    [SUPPORT_QUERY_STATUS.ASSIGNED]: "Assigned",
    [SUPPORT_QUERY_STATUS.IN_PROGRESS]: "In Progress",
    [SUPPORT_QUERY_STATUS.RESOLVED]: "Resolved",
    [SUPPORT_QUERY_STATUS.CLOSED]: "Closed",
  };
